//01
SELECT M.NOMBRE FROM PERSONAS M;

//02
SELECT * FROM PERSONAS M;

//03
SELECT N.MATRICULA, N.IMPORTE, ROUND(N.IMPORTE*1.02,2) FROM MULTAS N;

//04
SELECT LOWER(M.NOMBRE)AS  nombre_persona, M.DNI FROM PERSONAS M;

//05
SELECT M.NOMBRE AS c”DIGO_pERSONA, SUBSTR(M.DNI,1,4) FROM PERSONAS M;

//06
SELECT M.NOMBRE AS c”DIGO_pERSONA, SUBSTR(M.DNI,-4) FROM PERSONAS M;

//07
SELECT N.MATRICULA, N.IMPORTE, (N.IMPORTE*0.5) AS IMPORTE_BONIFICADO FROM MULTAS N;

//08
SELECT N.MATRICULA, N.IMPORTE, ROUND(N.IMPORTE*0.5) AS IMPORTE_BONIFICADO FROM MULTAS N;

//09
SELECT N.MATRICULA, N.IMPORTE, TRUNC(N.IMPORTE*0.5) AS IMPORTE_BONIFICADO FROM MULTAS N;

//10
SELECT E.DNI FROM MATRICULAS E;

//11
SELECT DISTINCT E.DNI FROM MATRICULAS E;

//12
SELECT M.NOMBRE FROM PERSONAS M ORDER BY M.NOMBRE ASC;

//13
SELECT M.NOMBRE FROM PERSONAS M ORDER BY M.NOMBRE DESC;

//14
SELECT * FROM MULTAS N ORDER BY N.IMPORTE DESC, N.LUGAR ASC;

//15
SELECT * FROM PERSONAS M WHERE ROWNUM <6;

//16
SELECT * FROM MULTAS N WHERE MATRICULA='6981-BMN';

//17
SELECT E.MATRICULA FROM MATRICULAS E WHERE DNI='451256522T';
SELECT * FROM MULTAS WHERE MATRICULA IN ('6578-BJS','A-5782-BK');
SELECT * FROM MULTAS WHERE MATRICULA='6578-BJS' OR MATRICULA='A-5782-BK';

SELECT * FROM MATRICULAS E, MULTAS N WHERE E.MATRICULA=N.MATRICULA AND E.DNI='451256522T';
SELECT * FROM MATRICULAS E INNER JOIN MULTAS N ON E.MATRICULA=N.MATRICULA WHERE E.DNI='451256522T';

//18
SELECT M.DNI FROM PERSONAS M WHERE NOMBRE='DORIS, MICHAEL';
SELECT E.MATRICULA FROM MATRICULAS E WHERE DNI='120365879U';
SELECT N.IMPORTE FROM MULTAS N WHERE MATRICULA='1206-DBN';


//19
SELECT * FROM MULTAS N WHERE IMPORTE>300;

//20
SELECT * FROM MULTAS N WHERE IMPORTE<300;

//21
SELECT * FROM MULTAS N WHERE IMPORTE>150 AND IMPORTE<350; //NO INCLUYE LOS VALORES
SELECT * FROM MULTAS N WHERE IMPORTE BETWEEN 150 AND 350, //ESTE INCLUYE LOS VALORES

//22
SELECT * FROM MULTAS N WHERE IMPORTE=50 OR IMPORTE=100 OR IMPORTE=200;
SELECT * FROM MULTAS N WHERE (IMPORTE=50 OR IMPORTE=100 OR IMPORTE=200) AND N.LUGAR='CASTELLANA 120'; //CUIDADO CON LOS OR Y LOS AND Y LOS PARENTESIS
SELECT * FROM MULTAS N WHERE IMPORTE IN (5,'100',200); //LOS ENTIENDE CON O SIN COMILLAS
SELECT * FROM MULTAS N WHERE IMPORTE IN (5,'100',200) AND N.LUGAR='CASTELLANA 120';

//23
SELECT * FROM PERSONAS WHERE NOMBRE LIKE 'R%';
SELECT * FROM PERSONAS WHERE SUBSTR (NOMBRE,1,1)='R';

//24
SELECT * FROM PERSONAS WHERE NOMBRE LIKE 'G%' OR NOMBRE LIKE 'F%';
SELECT * FROM PERSONAS WHERE SUBSTR (NOMBRE,1,1)='G' OR SUBSTR (NOMBRE,1,1)='F';

//25
SELECT * FROM PERSONAS WHERE UPPER (NOMBRE) LIKE 'DO%';
SELECT * FROM PERSONAS WHERE SUBSTR (NOMBRE,1,2)='DO';

//26
SELECT * FROM PERSONAS WHERE UPPER (NOMBRE) LIKE '%CIA%';
SELECT * FROM PERSONAS WHERE INSTR (NOMBRE,'CIA')>0; //SI PONES = TE BUSCA LOS QUE NO CONTIENEN ESA CADENA

//27
SELECT * FROM PERSONAS WHERE UPPER (NOMBRE) LIKE '%AN';
SELECT * FROM PERSONAS WHERE SUBSTR (NOMBRE,-2)='AN';

