//01
SELECT LOWER(M.FIRST_NAME ||' '|| M.LAST_NAME) NOMBRECOMPLETO FROM EMPLOYEES M;

//02
SELECT UPPER(M.FIRST_NAME ||' '|| M.LAST_NAME) NOMBRECOMPLETO FROM EMPLOYEES M;

//03
SELECT UPPER(M.FIRST_NAME ||' '|| M.LAST_NAME) NOMBRECOMPLETO FROM EMPLOYEES M WHERE MANAGER_ID IS NULL;
SELECT (M.FIRST_NAME ||' '|| M.LAST_NAME) NOMBRECOMPLETO FROM EMPLOYEES M WHERE MANAGER_ID IS NOT NULL;

SELECT DECODE(M.MANAGER_ID, NULL,
        UPPER(M.FIRST_NAME ||' '|| M.LAST_NAME),
        LOWER(M.FIRST_NAME ||' '|| M.LAST_NAME)) FROM EMPLOYEES M;
        
SELECT CASE WHEN M.MANAGER_ID IS NULL THEN UPPER(M.FIRST_NAME ||' '|| M.LAST_NAME)
    ELSE LOWER(M.FIRST_NAME ||' '|| M.LAST_NAME) END NOMBRE_COMPLETO
    FROM EMPLOYEES M;

//04
SELECT M.FIRST_NAME NOMBRE, LENGTH(M.FIRST_NAME) NºLETRAS FROM EMPLOYEES M;

//05
SELECT (M.FIRST_NAME ||' '|| M.LAST_NAME)NOMBRECOMPLETO,  LPAD((LOWER(EMAIL)), 10, '*')EMAIL FROM EMPLOYEES M;

//06
SELECT M.FIRST_NAME NOMBRE, LENGTH(M.FIRST_NAME) NºLETRAS, (SUBSTR(LAST_NAME,1,2)||SUBSTR(PHONE_NUMBER, 1,3)||SUBSTR(FIRST_NAME,-2)) EMP_PASSWORD FROM EMPLOYEES M;

//07
SELECT N.START_DATE FECHA_CONTRATA, TO_CHAR(START_DATE,'DD') DIA, TO_CHAR(START_DATE,'MM') MES, TO_CHAR(START_DATE,'YYYY') YEAR FROM job_history N;

//08
SELECT N.START_DATE FECHA_CONTRATA, ROUND(SYSDATE-N.START_DATE,2) DIAS, ROUND(MONTHS_BETWEEN(SYSDATE,N.START_DATE), 2) MESES FROM job_history N;

//09
SELECT M.FIRST_NAME NOMBRE, M.JOB_ID PUESTO, M.SALARY*12 SALARIO_ANUAL, ROUND(M.SALARY+M.SALARY*9.8/100,2) SUBIDA_PORCENTAJE_MENSUAL, TRUNC(12*(M.SALARY+M.SALARY*9.8/100),1) SUBIDA_PORCENTAJE_ANUAL FROM EMPLOYEES M;

//10
SELECT M.FIRST_NAME NOMBRE, M.LAST_NAME APELLIDO, 
    CASE SUBSTR(LAST_NAME,1,1) WHEN  'K' THEN SALARY+SALARY*0.1
    ELSE SALARY END SALARIO
    FROM EMPLOYEES M;
    
//11
SELECT * FROM EMPLOYEES ORDER BY HIRE_DATE DESC;

//12
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID=109;
    
//13
SELECT * FROM EMPLOYEES WHERE JOB_ID='AD_VP';

//14
SELECT * FROM EMPLOYEES WHERE HIRE_DATE<'01,01,2006';

//15
SELECT DISTINCT JOB_TITLE FROM JOBS;
SELECT JOB_ID, JOB_TITLE FROM JOBS WHERE JOB_TITLE='Programmer';
SELECT * FROM EMPLOYEES WHERE SALARY<5000 AND JOB_ID='IT_PROG';

//16
SELECT DECODE(M.MANAGER_ID, NULL,
        UPPER(M.FIRST_NAME ||' '|| M.LAST_NAME),
        LOWER(M.FIRST_NAME ||' '|| M.LAST_NAME)) FROM EMPLOYEES M WHERE SUBSTR(PHONE_NUMBER,1,3)=650;
        
SELECT CASE WHEN M.MANAGER_ID IS NULL THEN UPPER(M.FIRST_NAME ||' '|| M.LAST_NAME)
    ELSE LOWER(M.FIRST_NAME ||' '|| M.LAST_NAME) END NOMBRE_COMPLETO
    FROM EMPLOYEES M WHERE SUBSTR(PHONE_NUMBER,1,3)=650;

//17
SELECT TO_CHAR(HIRE_DATE,'MM'), E.* FROM EMPLOYEES E WHERE TO_CHAR(HIRE_DATE,'MM') IN (6,7,8);

//18
SELECT * FROM EMPLOYEES WHERE UPPER(LAST_NAME) LIKE '%W%' ORDER BY FIRST_NAME DESC;

//19
SELECT * FROM EMPLOYEES WHERE MANAGER_ID IS NULL;

//20
SELECT (M.FIRST_NAME ||' '|| M.LAST_NAME)NOMBRECOMPLETO,  LPAD((LOWER(EMAIL)), 10, '*')EMAIL FROM EMPLOYEES M WHERE SALARY BETWEEN 10000 AND 20000;

//21
SELECT * FROM EMPLOYEES WHERE JOB_ID IN ('IT_PROG','SA_REP','FI_ACCOUNT');

//22
SELECT * FROM EMPLOYEES WHERE JOB_ID IN ('IT_PROG','SA_REP','FI_ACCOUNT') AND SALARY BETWEEN 10000 AND 20000;

//23
SELECT * FROM EMPLOYEES WHERE JOB_ID IN ('IT_PROG','SA_REP','FI_ACCOUNT') OR SALARY BETWEEN 10000 AND 20000;

//24
SELECT * FROM EMPLOYEES WHERE SUBSTR(PHONE_NUMBER, 1,3) IN (515,011);
null
//25
SELECT M.FIRST_NAME NOMBRE, M.JOB_ID PUESTO, M.SALARY*12 SALARIO_ANUAL, ROUND(M.SALARY+M.SALARY*9.8/100,2) SUBIDA_PORCENTAJE_MENSUAL, TRUNC(12*(M.SALARY+M.SALARY*9.8/100),1) SUBIDA_PORCENTAJE_ANUAL FROM EMPLOYEES M
WHERE (JOB_ID='ST_CLERK' AND MANAGER_ID=122) OR (SALARY<3000) ORDER BY EMAIL ASC;

//26
SELECT M.FIRST_NAME NOMBRE, LENGTH(M.FIRST_NAME) NºLETRAS, (SUBSTR(LAST_NAME,1,2)||SUBSTR(PHONE_NUMBER, 1,3)||SUBSTR(FIRST_NAME,-2)) EMP_PASSWORD FROM EMPLOYEES M
WHERE UPPER(FIRST_NAME) LIKE 'A%' OR UPPER(FIRST_NAME) LIKE 'B%' OR UPPER(FIRST_NAME) LIKE'S%' OR UPPER(FIRST_NAME) LIKE'N%' ;

//27
SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE '_____';

//28
SELECT * FROM EMPLOYEES WHERE MONTHS_BETWEEN(SYSDATE, HIRE_DATE)>(20*12);

//29
SELECT * FROM EMPLOYEES WHERE phone_numbeR LIKE ('%423%');

//30
SELECT DISTINCT SALARY FROM EMPLOYEES ORDER BY SALARY DESC;


    











