CREATE TABLE ARTISTA(
COD_ARTISTA NUMBER(30) NOT NULL PRIMARY KEY,
NOMBRE VARCHAR2(50) NOT NULL,
TIPO_ARTISTA VARCHAR2(8) NOT NULL,
CONSTRAINT CK_TIPO_ARTISTA CHECK (TIPO_ARTISTA IN('GRUPO','CANTANTE'))
);
//CONSTRAINT Ck_CANTANTE_GRUPO check (TIPO_ARTISTA='CANTANTE' OR TIPO_ARTISTA='GRUPO')

CREATE TABLE DISCOS(
COD_DISCO NUMBER(30) NOT NULL PRIMARY KEY,
NUM_CANCIONES NUMBER(30) NOT NULL,
TITULO VARCHAR2(50) NOT NULL,
TIPO_DISCO VARCHAR2(6) NOT NULL,
CONSTRAINT CK_TIPO_DSICO CHECK (TIPO_DISCO IN('VINILO','CD'))
);

CREATE TABLE DISCOSXARTISTA(
COD_ARTISTA_GRUPO NUMBER(30),
CONSTRAINT FK_ARTISTA_GRUPO
FOREIGN KEY (COD_ARTISTA_GRUPO) REFERENCES ARTISTA(COD_ARTISTA),
COD_DISCO NUMBER(30),
CONSTRAINT FK_COD_DISCO
FOREIGN KEY (COD_DISCO) REFERENCES DISCOS(COD_DISCO),
PRIMARY KEY(COD_ARTISTA_GRUPO,COD_DISCO)
);

